#server
server:
  port: 10000

#files
file:
  directory: "C:/upload/"

#jdbc
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: hr
    password: hr

  #jpa
  jpa:
    hibernate:
      ddl-auto: update

    #jpa format
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  #log
  output:
    ansi:
      enabled: always

  devtools:
    livereload:
      enabled: true

  freemarker:
    cache: false
    
#  # H2 Setting Info (H2 Console에 접속하기 위한 설정정보 입력)
#  h2:
#    console:
#      enabled: true  # H2 Console을 사용할지 여부 (H2 Console은 H2 Database를 UI로 제공해주는 기능)
#      path: /h2-console  # H2 Console의 Path
#  # Database Setting Info (Database를 H2로 사용하기 위해 H2연결 정보 입력)
#  datasource:
#    driver-class-name: org.h2.Driver  # Database를 H2로 사용하겠다.
#    url: jdbc:h2:~/test  # H2 접속 정보
#    username: sa  # H2 접속 시 입력할 username 정보 (원하는 것으로 입력)
#    password:  # H2 접속 시 입력할 password 정보 (원하는 것으로 입력)

file-root: "C:/upload/"